<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LTIN186256" name="com.testcases.framework.BomgarTestScenerio" tests="12" failures="0" timestamp="16 Jan 2023 05:16:45 GMT" time="566.886" errors="1">
  <testcase name="appClose" time="327.745" classname="com.testcases.framework.BomgarTestScenerio">
    <error type="org.sikuli.script.FindFailed" message="C:/Images For Sikuli/EndSession.png: (515x66) in R[0,0 1920x1080]@S(0)">
      <![CDATA[FindFailed: C:/Images For Sikuli/EndSession.png: (515x66) in R[0,0 1920x1080]@S(0)
  Line 2226, in file Region.java

at org.sikuli.script.Region.wait(Region.java:2226)
at com.testcases.framework.BomgarTestScenerio.appClose(BomgarTestScenerio.java:864)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- appClose -->
  <testcase name="sikuliTestCase001" time="11.634" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="sikuliTestCase002" time="19.269" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="sikuliTestCase003" time="11.989" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="sikuliTestCase004" time="41.859" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="sikuliTestCase005" time="33.202" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="sikuliTestCase006" time="37.838" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="sikuliTestCase007" time="16.414" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="sikuliTestCase008" time="17.039" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="siKuliTestCase009" time="9.706" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="sikuliTestCase010" time="17.774" classname="com.testcases.framework.BomgarTestScenerio"/>
  <testcase name="sikuliTestCase0011" time="22.417" classname="com.testcases.framework.BomgarTestScenerio"/>
</testsuite> <!-- com.testcases.framework.BomgarTestScenerio -->
